apiVersion: v1
kind: Namespace
metadata:
  name: dogcompetitions

# ===== api-gateway =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dogcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nelet/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: DOG_SERVICE_BASEURL
              value: "dog-service:8080"
            - name: PERSON_SERVICE_BASEURL
              value: "person-service:8080"
            - name: COMPETITION_SERVICE_BASEURL
              value: "competition-service:8080"
            - name: HISTORY_SERVICE_BASEURL
              value: "history-service:8080"
            - name: GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: clientid
            - name: GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: clientsecret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dogcompetitions
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080