apiVersion: v1
kind: Namespace
metadata:
  name: dogcompetitions

# ===== Persistent Volumes for MongoDBs =====
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: competitiondb-pvc
  namespace: dogcompetitions
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi

# ===== competitiondb =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: competitiondb
  namespace: dogcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: competitiondb
  template:
    metadata:
      labels:
        app: competitiondb
    spec:
      containers:
        - name: competitiondb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: competitiondb-storage
              mountPath: /data/db
      volumes:
        - name: competitiondb-storage
          persistentVolumeClaim:
            claimName: competitiondb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: competitiondb
  namespace: dogcompetitions
spec:
  selector:
    app: competitiondb
  ports:
    - port: 27017
      targetPort: 27017

# ===== competition-service =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: competition-service
  namespace: dogcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: competition-service
  template:
    metadata:
      labels:
        app: competition-service
    spec:
      containers:
        - name: competition-service
          image: nelet/competition-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_HOST
              value: "competitiondb"
---
apiVersion: v1
kind: Service
metadata:
  name: competition-service
  namespace: dogcompetitions
spec:
  selector:
    app: competition-service
  ports:
    - port: 8080
      targetPort: 8080