apiVersion: v1
kind: Namespace
metadata:
  name: dogcompetitions

# ===== Persistent Volumes for MongoDB =====
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persondb-pvc
  namespace: dogcompetitions
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
      
# ===== persondb =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persondb
  namespace: dogcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persondb
  template:
    metadata:
      labels:
        app: persondb
    spec:
      containers:
        - name: persondb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: persondb-storage
              mountPath: /data/db
      volumes:
        - name: persondb-storage
          persistentVolumeClaim:
            claimName: persondb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: persondb
  namespace: dogcompetitions
spec:
  selector:
    app: persondb
  ports:
    - port: 27017
      targetPort: 27017

# ===== person-service =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  namespace: dogcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: nelet/person-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_HOST
              value: "persondb"
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: dogcompetitions
spec:
  selector:
    app: person-service
  ports:
    - port: 8080
      targetPort: 8080