name: Docker Compose Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker (if pushing)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        run: |
          docker compose -f APT/docker-compose.yml build \
            --build-arg GOOGLE_CLIENTID=${{ secrets.GOOGLE_CLIENTID }} \
            --build-arg GOOGLE_CLIENTSECRET=${{ secrets.GOOGLE_CLIENTSECRET }}
          docker compose -f APT/docker-compose.yml up -d
